---
title: ""
author: "Francisco"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
output: 
  html_document: 
    fig_width: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = F,warninsg = F)
```

```{r includes}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("dplyr","pscl","stringr","pbapply","ggplot2")
```

```{r initialize}
# Establecer el path del repositorio y listar los archivos csv con los votos
path <- "~/Documents/GitHub/votaciones-diputados-argentina/data/csv/"
files <- bind_rows(as_data_frame(list.files(pattern = "votaciones_votos-.*.csv$",path = path)))
```

```{r import data}
# Generar una lista con cada elemento siendo un periodo de votacion
sesiones_completas <- lapply(files$value,function(x){
  yr <- as.integer(str_extract(x,"\\d{4}")) # Extrae el anio de votacion
  yrs <- cbind(yrs,yr)
  yr_votes <- read.csv(paste0(path,x),sep = ",") # Importa el archivo
  yr_votes <-  cbind(yr_votes,periodo=yr) # Le agrega la columna con el periodo de votacion
  yr_votes
})
# Transformar la lista en un dataset unico
sesiones_completas <- bind_rows(sesiones_completas)
sesiones_completas <- sesiones_completas %>% arrange(periodo,voto,voting_id,legislador_id)
# Listar los periodos
periodos <- sesiones_completas %>% distinct(periodo) %>% first()
```

```{r}
sesiones_completas <- sesiones_completas %>% arrange(voto,periodo,legislador_id,voting_id,bloque_id)
info <- pblapply(periodos,function(x){
  votos_periodo <- sesiones_completas[sesiones_completas$periodo == x,]
  # votos_periodo <- votos_periodo %>% arrange(periodo,voting_id,voto,nombre)
  nvotos_periodo <- dim(votos_periodo)[1]
  legis.names <- as.vector(unique(votos_periodo[,'legislador']))
  nlegis <- length(legis.names)
  legis.partidos <- as.vector(votos_periodo[rownames(unique(votos_periodo['legislador'])),
                                            'bloque'])
  actas.names <- as.vector(as.character(unique(votos_periodo[,'voting_id'])))
  nactas <- length(actas.names)
  niveles <- unique(votos_periodo[,'voto'])
  niveles <- sort(niveles)
  notInLegis <- match('AUSENTE', niveles)
  yea <- match('AFIRMATIVO', niveles)
  nay <- match('NEGATIVO', niveles)
  abstencion <- match('ABSTENCION', niveles)
  data <- matrix(, nlegis, nactas)
  for (n in 1:nvotos_periodo) {
    nombre <- legis.names == votos_periodo[n, 'legislador']
    acta <- actas.names == votos_periodo[n, 'voting_id']
    nivel <- match(votos_periodo[n, 'voto'], niveles)
    data[nombre, acta] <- nivel
  }
  legis.data <- data.frame(party=legis.partidos)
  row.names(legis.data) <- legis.names
  desc <- paste('Votos de diputados', x)
  rData <- rollcall(data, yea=yea, nay=nay, missing=abstencion,
                            notInLegis=notInLegis, legis.names=legis.names, vote.names=actas.names,
                            legis.data=legis.data, vote.data=NULL, desc=desc, source=NULL)

  # El algoritmo de ideal points en si
  fitted <- ideal(rData, normalize=FALSE,impute = T)
  outcome <- fitted$xbar
  outcome <- cbind(outcome,periodo=votos_periodo$periodo[1])
  outcome <- as.data.frame(outcome)
  names(outcome) <- c("idp","periodo")
  outcome <- add_rownames(outcome,"nombre")
  # list(n_votos=nvotos_periodo,votos=votos_periodo,legis.names=legis.names,n_legis=nlegis,legis.partidos=legis.partidos,actas.names=actas.names,n_actas=nactas,niveles=niveles,yea=yea,nay=nay,abstencion=abstencion,notInLegis=notInLegis,data=data)
})

idps_periodos_todos <- bind_rows(info)
```

```{r}
write.table(idps_periodos_todos,"idps_2019_sinnormalizar.csv",row.names = F,sep = ",")
```

```{r}
idps_periodos_todos %>% arrange(idp) %>% 
  ggplot(aes(x = as.numeric(row.names(idps_periodos_todos)),idp)) + 
  geom_point() +
  facet_wrap(~periodo)

idps_anteriores <- read.csv("/Users/panchtox/gdrive/diputados/diputados02-08-13_19-23.csv")

idps_anteriores %>% inner_join(idps_periodos_todos,by=c("nombre","year"="periodo")) %>% 
  ggplot(aes(idp.x,idp.y)) + 
  geom_point(alpha=0.6) +
  facet_wrap(~year)

```

```{r}
idps_periodos_todos %>% filter(periodo==2006) %>% arrange(idp) %>% View()
```

