---
title: ""
author: "Francisco"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
output: 
  html_document: 
    fig_width: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = F,warning = F)
```

```{r includes}
if (!require("pacman")) install.packages("pacman")
# igraph es la libreria de grafos, threejs tiene herramientas para graficar objetos en js y htmlwidgets lo uso para exportar una pagina html a un archivo
pacman::p_load("dplyr","igraph","threejs","tidyr","htmlwidgets")
```

```{r}
# Renombrar las columnas para igraph
distancias_periodos_todos <- distancias_periodos_todos %>% 
  rename(Source=desde,Target=hacia,weight=idps_dist,period=periodo)
```

```{r}
# Generar el listado de legisladores y sus atributos (el del script anterior falla por algun motivo)
legisladores <- distancias_periodos_todos %>% gather(variable,legislador,-c(weight,period)) %>%
  distinct(legislador) %>% 
  inner_join(legislador_bloque_periodo)
```


```{r}
# Generar un objeto grafo por cada periodo, con atributos que luego usamos
grafos_por_periodo <- pblapply(periodos,function(x){
  # Extraer las distancias para un periodo determinado
  distancias_periodo <- distancias_periodos_todos[distancias_periodos_todos$period == x,]
  # Extraer los legisladores para el mismo periodo
  diputades_periodo <- legisladores[legisladores$periodo == x,]
  # Despues de probar puntos de corte para borrar edges
  punto_corte <- 0.7
  # Genero el grafo desde el dataframe
  g <- graph_from_data_frame(vertices = diputades_periodo$legislador,
                             d = distancias_periodo[,c(1:3)],directed = F)
  # Agrego atributos a los vertices
  V(g)$legislador_id <- diputades_periodo$legislador_id
  V(g)$bloque <- diputades_periodo$bloque
  V(g)$bloque_id <- diputades_periodo$bloque_id
  V(g)$periodo <- diputades_periodo$periodo
  V(g)$betweenness <- betweenness(g,directed = F,normalized = T)
  # Aca las etiquetas
  g <- set.vertex.attribute(g,"label",
                                value = paste0("<b>",V(g)$name,"</b>","<br>",V(g)$bloque))
  
  gsimp <- simplify(g)
  # Borro los dedges que implican mas distancia que el punto de corte
  gsimp <- delete_edges(g, E(g)[weight > punto_corte])
  # Simplifico el grafo para evitar duplicados
  gsimp <- simplify(gsimp)
  
})
```


```{r}
# Generar las comunidades, visualizaciones del grafo y subgrafos
lapply(grafos_por_periodo,function(g){
  periodo <- V(g)$periodo[1]
  path <- paste0("grafos_",periodo)
  dir.create(path)
  g <- delete.vertices(g,V(g)[degree(g)<3]) # Para que no queden nodos perdidos en el espacio
  x <- fastgreedy.community(g, weights = (1/E(g)$weight)) # Detectar comunidades
  i <- membership(x)
  g <- set.vertex.attribute(g,"color",value = rainbow(length(x))[i]) # Mapea las comunidades a colores
  lapply(1:length(x),function(i){ # Iterador para guardar los subgrafos y csv de las comunidades
	  archivo_subgrafo <- paste0("subgrafo_",periodo,"_",i,".html")
	  archivo_csv <- paste0("lista_",periodo,"_",i,".csv")
	  gs <- as.undirected(subgraph(g, which(x$membership==i)))
	  saveWidget(graphjs(gs), file = paste0(getwd(),"/",path,"/",archivo_subgrafo))
	  write.table(V(gs)$label,paste0(getwd(),"/",path,"/",archivo_csv),row.names = F,sep = ",")
	})
  # La visualizacion de un grafo es muy dependiente del layout. Para encontrar una buena proyeccion
  # Genero k grafos, cada uno con un layout distinto para luego elegir.
  # Cada grafo queda guardado en una carpeta del periodo y esta numerado de acuerdo a k
  k <- 2
  lapply(1:k,function(i){ # Iterador para generar grafos con diferente layout
    archivo_grafo <- paste0("grafo_",i,".html")
    filepath <- paste0(getwd(),"/",path,"/",archivo_grafo)
    l <- layout_with_fr(g,dim = 3) # Calcula un layout
    # Guarda el grafo generado por graphjs
    saveWidget(graphjs(g,layout = l,vertex.size = (V(g)$betweenness+1)),file =filepath)
  })
})
```



